name: Build

on: [pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "dota2-rpc-client",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
    steps:
    - uses: actions/checkout@v2
    - name: Download libgtk-3-dev
      run:   |
            if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt install -y libgtk-3-dev
            else
              echo "$RUNNER_OS don't need this library!"
            fi
      shell: bash
    - name: Fetch CMake
      uses: lukka/get-cmake@v3.21.2
    - name: Download vcpkg
      uses: lukka/run-vcpkg@v10.3
      with:
        vcpkgGitCommitId: 'f93ba152d55e1d243160e690bc302ffe8638358e'
        runVcpkgInstall: true
    - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'default'
        buildPreset: 'release'
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        path: ./build/default/Release
        name: ${{ matrix.config.artifact }}