name: GitHub Pages

on:
  push:
    branches:
    - web

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      working-directory: ./web
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: ./web
      run: npm install

    - name: Build
      working-directory: ./web
      run: npm run build:prod

    - name: Deploy
      working-directory: ./web
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/dota2-rpc-client
        enable_jekyll: true